### PR TITLE
Add support for animated GIFs (#68)

### PR DESCRIPTION
**Pull request by Ozerich**
Added support for animated GIFs and videos

Example of usage:
screenshot

### CODE REVIEW

**Comment by Ozerich** [comment]
Ready to merge

**Comment by antmonnier** [comment]
Can we also add support for video poster images?

I would like to be able to use sth like this:
```
<video poster="../images/031-access-settings.png">
  <source src="../images/031-access-settings.mp4" type="video/mp4"/>
  <source src="../images/031-access-settings.webm" type="video/webm"/>
</video>
```

**Comment by Ozerich** [comment]
I've added support for video poster images.
It was impossible before, because gatsby plugin cannot handle video posters. But my colleague added this functionality to plugin and published it on npm as separate npm package. So, it works now

**Comment by antmonnier** [comment]
Closes #68

**Comment by antmonnier** [comment]
2 issues:

- this branch breaks image display:
image

- when a video is added to a page with the `documentation` layout: 
image
a warning is shown in the browser console: 
image

**Comment by antmonnier** [comment]
Hi @Ozerich This PR and https://github.com/HubRise/website/pull/74 are preventing our tech writers to publish documentation, can you prioritize these 2?

**Comment by Saranchenkov** [comment]
I've fixed image displaying and warning in console

**Comment by Ozerich** [comment]
I've fixed image display and warning in console

**Pull request merged**
