### PR TITLE
Feature/contact form

### PR DESCRIPTION
**Pull request by Ozerich**
How to test locally:

1. create file `.env.development` in the root directory with env variable `RECAPTCHA_SITE_KEY=`
2. go to `/server` directory, create file `.env` and specify the same variables as in `/server/.env.example`
3. install dependencies in `/server` directory via `yarn`
4. run server via `node /server/index.js`
5. run gatsby via `yarn start:dev`

### CODE REVIEW

**Comment by antmonnier** [comment]
Closes #51

**Comment by antmonnier** [comment]
Hi @Ozerich 

Good work on that one. There are just a few inherited usability issues we need to address:

- After submitting the form, fields are "frozen" and we cannot use the form again until we reload the page

- Validations that fields should not be empty should only fire when you submit the form, not when you focus on them. Otherwise you get this situation just by tabbing through the fields or touching them on the phone:
image

- After submission, there should be a message displayed, maybe in a ribbon over the screen like this:
image
Just change the color & font style to match the rest of the site.

- Actual copy:
  * "Your message has been sent. We'll reply to you shortly." / "Votre message a bien été envoyée et nous allons vous répondre rapidement"
  * "Oops... An error occurred while sending your message, please try again or email us at contact@hubrise.com" / "Zut... Une erreur s'est produite durant l'envoi de votre message. Veuillez réessayer ou écrivez-nous directement sur contact@hubrise.com"

- The ribbon should disappear after a few seconds. If an error occurred, make sure the form is still visible and the fields are not deleted. If successful, close the form popup.

**Comment by Ozerich** [comment]
I've fixed form isues and added notifications
But I have issue with emails. I get the following message from SendGrid API : 
"The provided authorization grant is invalid, expired, or revoked"
Did you do something with API key?

**Comment by antmonnier** [comment]
I've just noticed the captcha watermark seems to appear on all pages:
image

Any way we can remove it?

**Comment by antmonnier** [comment]
Note for self: waiting for this issue to be done before merging this PR: https://github.com/HubRise/manager/issues/66

**Comment by Ozerich** [comment]
Fixed

**Comment by antmonnier** [comment]
Thanks Vital, I'll now keep this PR on hold until work is completed by the Rails developer.

**Pull request merged**
