### PR TITLE
[LIGHTSPEED TRANSLATION] FR version

### PR DESCRIPTION
**Pull request by janaina-wittner**

### CODE REVIEW

**Comment by janaina-wittner** [comment]
@antmonnier, please check the FAQ > Create Ref Codes > Deals sections. I think others have been edited correctly now to match the Lightspeed back office updates.
[Lightspeed Restaurant](https://github.com/HubRise/support/wiki/Test-Accounts#lightspeed-restaurant)
Back-office:
https://manager.lsk.lightspeed.app/
Email / Password: [integration@hubrise.com](mailto:integration@hubrise.com) / OZ5WfC2B

**Comment by antmonnier** [comment]
Done, I've also slightly updated the other sections. See my [changes here](https://github.com/HubRise/website/pull/892/commits/211832004ab2955ba162710871ccd868540fb98f).

**Comment by janaina-wittner** [comment]
This is ready for merge

**Comment by janaina-wittner** [comment]
I noticed a typo in the EN version: Configuration page > missing space between these two words "selectEnabled"
https://www.hubrise.com/apps/lightspeed-restaurant/configuration#orders

**Comment by antmonnier** [comment]
> I noticed a typo in the EN version: Configuration page > missing space between these two words "selectEnabled"

Looks good to me:
image

**Comment by antmonnier** [comment]
Great job! This is going live this morning.

**Pull request merged**
