### PR TITLE
 [Uber Eats] Update Connect to HubRise

### PR DESCRIPTION
**Pull request by janainawittner**

### CODE REVIEW

**Comment by janainawittner** [comment]
CC @atorin My understanding of our Style Guide is that we should link page titles and not a generic "Documentation" term.
Also, I linked directly to the Locations page as this is what we are referring to here but we could have left the link on Accounts and Locations instead. The purpose of this change, was more a stylistic one....

**Comment by janainawittner** [comment]
This has been closed but I cannot see the change in the site: https://www.hubrise.com/apps/uber-eats/connect-hubrise/
How can I get this pull request opened again not to forget it?

**Comment by atorin** [comment]
@janainawittner I'm not sure what happened here either, but I had your same doubt. 
But just to be on the safe side, I had already included this change again into #174 (https://github.com/HubRise/website/pull/174/commits/51010b748b4edf844a444ee17b94be698cd9853f)
I took the liberty of:
- Changing "HubRise Locations" -> "Locations" (as this is the name of the page).
- Changing the URL to a relative path. 

Let me know if you don't agree with those changes so that I can revert them both on Uber and Deliveroo. Thanks!

**Comment by janainawittner** [comment]
@atorin, perfect then. Let's leave this Pull Request closed then.

**Pull request merged**
