### PR TITLE
Pixel Point

### PR DESCRIPTION
**Pull request by janainawittner**

### CODE REVIEW

**Comment by janainawittner** [comment]
@ReynardtDeminey, when you create a branch, please think of creating a pull request too. This is the way we do it to make sure we don't have an orphan branch. 
You said in your Trello note that you had finished the Web API import. Have you also finished the Win API import? 
Might I review both?

**Comment by ReynardtDeminey** [comment]
> @ReynardtDeminey, when you create a branch, please think of creating a pull request too. This is the way we do it to make sure we don't have an orphan branch.
> You said in your Trello note that you had finished the Web API import. Have you also finished the Win API import?
> Might I review both?

I did finish the Windows API, but as you know there are still some info missing. You can review both

**Comment by janainawittner** [comment]
@antmonnier, I think it's ready now.

**Comment by janainawittner** [comment]
@antmonnier, I think it's ready now.

**Comment by janainawittner** [comment]
@antmonnier, I think it's ready now, with the FR Apps page update.

**Pull request merged**
