### PR TITLE
[Popina] Docs first draft

### PR DESCRIPTION
**Pull request by albert9168**
See #803

### CODE REVIEW

**Comment by janaina-wittner** [comment]
@antmonnier, we need this documentation online urgently :-(

**Comment by antmonnier** [comment]
Hi @albert9168 I've reviewed your PR but decided it would be easier to maintain this documentation in French. I've translated + added some new content. We'll translate it back to English later, when needed.

**Comment by albert9168** [comment]
Hi @antmonnier! OK thanks for letting me know! Do we have a way to tag which version is the source, and which version is the target (translated) for each app?

**Comment by antmonnier** [comment]
Hi @albert9168 The convention is to put an empty `.TRANSLATED` file in the target language's folder.

**Pull request merged**
