### PR TITLE
Docs: JSON Guide [WIP]

### PR DESCRIPTION
**Pull request by atorin**
Add "Understanding HubRise Logs" document.

### CODE REVIEW

**Comment by antmonnier** [comment]
Thanks @atorin , a few things:

- HTML tables can be done in markdown: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables - do you prefer using HTML?

- Bullet points: no newlines between them (as it wraps each `li` into a `p`)

- You can also insert your images and liaise with Janaina to get them reworked by our designer to fit the branding.

**Comment by atorin** [comment]
Hi @antmonnier! 

- I don't have any preference for the tables format, that's the format that the script spit out. I'll use Markdown then. 
- Noted for bullet points.
- Images still need to be fixed. I'll do that in one of the next commits.

On a separate note, do I have to change any config file in order to see a preview of the new pages in the local instance of the website?

**Comment by antmonnier** [comment]
> On a separate note, do I have to change any config file in order to see a preview of the new pages in the local instance of the website?

Your new pages should be visible on: http://localhost:8000/docs/hubrise-logs

If you make a change and save, the website should automatically refresh with the new content after a few seconds. Sometimes a manual refresh is needed though.

**Comment by antmonnier** [comment]
I'm assigning this PR to you now so that I know you're still working on it. Please assign me for review when you're done.

Janaina is working on the documentation structure now, so would be good to merge this PR with the images today/tomorrow.

You will still be able to continue working on it after it is merged, by creating a new PR.

**Pull request merged**
