### PR TITLE
Lg20201110 woocommerce documentation

### PR DESCRIPTION
**Pull request by janainawittner**

### CODE REVIEW

**Comment by janainawittner** [comment]
@LeGaby 

I am not going to give any feedback on this one as there is little to say. My feedback is very much what I have already said about Shopify. The description part is more clear on this one. Even if you speak about shipping here too, we undestand as you refer to "manage.... shipping".  I thus left it as is. 

I did a lot of cut/paste for the rest of the content. Indeed, as I understand the WooCommerce integration is being built with the exact same specification as Shopify.

Note that I moved the **Prerequisites** section to the very end. This is actually something we had agreed on with Antoine for the new documentation (you will see it on Uber Eats for instance). I forgot to do it on Shopify.

Not sure why but when I leave the Meta Title and description on the Zelty FAQ, the whole site on http://localhost:8000/apps crashes. I saw some error line 7, removed these lines and it compiles fine. I comminted this update here but it should definitely not be merged. Can you try and undestand what is happening so this does not get through by accident ?

**Comment by janainawittner** [comment]
@LeGaby, feel free to send it to Antoine to be merged. Please make a note saying that we assumed this integration will have the exact same features as Shopify.

**Comment by antmonnier** [comment]
> Not sure why but when I leave the Meta Title and description on the Zelty FAQ, the whole site on http://localhost:8000/apps crashes. I saw some error line 7, removed these lines and it compiles fine. I comminted this update here but it should definitely not be merged. Can you try and undestand what is happening so this does not get through by accident ?

@janainawittner I've just fixed it on `master`, and merged the change into this PR. The problem was that the Zelty META description contained a colon. As `:` has a special meaning in YAML, the description had to be quoted.

**Comment by antmonnier** [comment]
@LeGaby Can I merge? Let me know when you're ready!

**Comment by LeGaby** [comment]
@antmonnier, you can merge this one!

**Pull request merged**
