### PR TITLE
[DELICITY] Connexion page set up

### PR DESCRIPTION
**Pull request by janaina-wittner**

### CODE REVIEW

**Comment by antmonnier** [comment]
Hello @fsantucci when you're ready, you can assign this PR to me.

**Comment by fsantucci** [comment]
It is just missing the screenshots. I will add them this week and confirm
once done.


Le mar. 18 juil. 2023 à 12:43, Janaina Wittner ***@***.***> a
écrit :

**Comment by janaina-wittner** [comment]
I suppose the Delicity back office is in FR only. If you have an EN version, please make sure to take both EN and FR screenshots.
You have full instructions on Screenshooting here: https://www.hubrise.com/contributing/screenshots-guide/

Antoine changed things slightly recently but I had no time to update our online documentation. It is not necessary now to include the **en** or **fr** tags on the file name. Images have the exact same name in both languages. They are placed in their respective **en** and **fr** > **images** folders instead.

**Comment by antmonnier** [comment]
@fsantucci just a reminder about this PR :)

**Comment by fsantucci** [comment]
@antmonnier Just assigned this one to you. I'm not sure if I should push something or Commit are enough?

**Comment by antmonnier** [comment]
@fsantucci You have already pushed your commits and assigned the PR to me, so now it's on my side. Thanks!

**Pull request merged**
