### PR TITLE
Documentation layout: add support for inline images (#67)

### PR DESCRIPTION
**Pull request by Ozerich**
Added workaround to use JPG/PNG images inside text
We can use it in the following ways:

1. `<InlineImage width="20" height="20">Alt text</InlineImage>`
2. `<InlineImage width="20" height="20">Alt text</InlineImage>`

For example:
`Account-level catalogs are accessible by all the locations of the account. <InlineImage width="20" height="20">Alt text</InlineImage> They are useful when several locations share a common catalog of products.`

As you can see, we should specify image width and height to correctly display in text.

### CODE REVIEW

**Comment by Ozerich** [comment]
Ready to merge

**Comment by antmonnier** [comment]
Closes #67

**Comment by antmonnier** [comment]
Could we simplify a bit the usage of this feature, for instance:

```
To view the order details, select the Order Card. Click the close icon <InlineImage alt="Close icon" src="../images/close.png"/> or anywhere outside the Order Card to close it.
```
?

ie let the code figure out the size, not the user, and simplify the syntax a bit. What do you think @Ozerich ?

**Comment by antmonnier** [comment]
Increased the priority of this PR and #72

**Comment by Ozerich** [comment]
> Could we simplify a bit the usage of this feature, for instance:
> 
> ```
> To view the order details, select the Order Card. Click the close icon
> <InlineImage alt="Close icon" src="../images/close.png"/> or anywhere
> outside the Order Card to close it.
> ```
> 
> ie let the code figure out the image size and simplify the syntax a bit. What do you think @Ozerich ?

No, we can't. Gatsby plugin that parse image url in markdown doesn't support such syntax. Plugin understands only two variants that were mentioned in first comment:
1. `Alt text`
2. `Alt text`

**Pull request merged**
