### PR TITLE
[GLOBAL UPDATES] tiny updates

### PR DESCRIPTION
**Pull request by janaina-wittner**

### CODE REVIEW

**Comment by janaina-wittner** [comment]
@antmonnier, this PR was not yet assigned to you :-(
I was still working on it :-(
Please wait for me to tell you I am done, OK?
There are a lot of PR in the list you can attend to other than the ones I am working on :-)

**Comment by janaina-wittner** [comment]
I need UPX back online. 
They are still in business. 
Just change the URL in the Overview page. 

EN link: https://upxp.io/
FR link: https://upxp.io/programme-de-fidelite/

**Comment by antmonnier** [comment]
Oops I missed that it was not yet assigned to me. Will create a new PR to restore UPXP and assign it to you.
Don't commit anything to this branch, as it has already been merged.

**Comment by janaina-wittner** [comment]
Yes...

**Comment by janaina-wittner** [comment]
Thanks but have you fixed the URLs or should I remember to do this later?

**Comment by antmonnier** [comment]
I've just reverted the deletion of the upxp folder, and the removal of upxp from apps.yaml. I've not changed anything else.

**Pull request merged**
