### PR TITLE
[CATALOG MANAGER] Translation EN>FR

### PR DESCRIPTION
**Pull request by janaina-wittner**

### CODE REVIEW

**Comment by janaina-wittner** [comment]
In crowdin, catalog.md looks fine in the Translation columen and the TM but somehow it is not in view mode. 

Here is the translation:
Pour plus d'informations, consultez les pages d'aide HubRise [Comptes](/docs/comptes) et [Points de vente](/docs/points de vente).

Here is what it looks like when we input it in Webstorm.
Pour plus d'informations, consultez les pages d'aide HubRise [Comptes](/docs/comptes) et /[Points de vente]/(/docs/points de vente).

**Comment by antmonnier** [comment]
@janaina-wittner This PR is not assigned to me, are you still working on it?

**Comment by janaina-wittner** [comment]
yes... I am still working on it :-(

**Comment by janaina-wittner** [comment]
Hi @antmonnier, this is ready now. 
Please make sure to edit strings on the Crowdin TM editor if you decide to change any of the translations and only re-translate the source file after that. From the Crowdin translation mode, you cannot delete approved translations and I have approved them.

**Comment by janaina-wittner** [comment]
Est-ce que tu peux publier ça rapidement ? 
J'en ai besoin pour un prospect, 4 point de ventes... et il ne parle pas un mot d'anglais.

**Pull request merged**
