### PR TITLE
20200722 zelty

### PR DESCRIPTION
**Pull request by ReynardtDeminey**

### CODE REVIEW

**Comment by ReynardtDeminey** [comment]
Janaina. I hove done the documentation in terms of the demo checklist that we did during the call with Benjamin. I suspect that there are still many more things to add. We should also have a look at the possible faq's that might arise from the customers perspective. Also please check that my account on HubRise is connected to the test account. I remember I gave you the account details, but when logged in I can't see it.
Thanks

**Comment by janainawittner** [comment]
@ReynardtDeminey, feel free to create test accounts on HubRise. I have given you access to the account I generally use for testing called:  Compte The HubRise Restaurant (z6q31). 
I might have removed your permission to the account. Sorry about this. 

Regarding the work, we need to speak about what we need again. 
I have done a lot of editing, and added content. You knew most of the thing to include the the style is not always there and guidelines I have given you before have not been followed. 

Here are a few markdown comments. You could include these in our contributing guide but I think you can also figure it out by checking how things were done elsewhere. 
- Bullet points in markdown should be represented as - and not * to keep consistent with what we have been doing before.
- When creating lists in markdown. Please use - and not *.
- When creating lists in markdown, use 1. everywhere.  Makrdown will sequence them 1. 2. 3. as needed in the page.

Comments on the style and content:
- Bold should be used for UI items and for words you need to emphasis. **Click** for instance is not a word I would ever expect to see in bold. I suggested at some point that we could keep your way of using bold to help readers go through the content faster but we discussed it internally and prefer to keep is as we use to have it. So please, make sure to follow guidelines. If you find the the style guide is not clear, feel free to update it.
- Sometimes you included **Click**  in bold and UI items were not bold which is definitely a problem.
- A full stop was out of place. 
- Try to use lists or bullet points more often when giving step by step information.
- Stick to the existing structure we have for POS integrations. I had to change a file name to mapping-epos-codes.md
- I would like you to take a bit more time to test and understand how things work to be in a better position to write. It might imply exporting menus for instance and checking what is transferred in the logs and what is not. For instance; Tags are not transferred over. This information is important and should be documented. Antoine had specified it in the integration sheet.
- etc. 

I think the best is for you to look at the work I have done and we schedule a call. You have my calendly link, so please do not hesitate to schedule it for tomorrow.

Cheers, Janaina

**Comment by janainawittner** [comment]
@antmonnier, if you want to have a look, it's ready as far as I am concerned. 
@ReynardtDeminey, please confirm when you have proofread it. I am not an English native and am not at ease.

**Comment by janainawittner** [comment]
@antmonnier, @ReynardtDeminey, just made more changes, sorry. Hope neither of you have not started working on this as there has been a lot of structure changes. I think it looks better now. I will update other documentations accordingly.

**Pull request merged**
