### PR TITLE
[Apps] Modify search matching algorithm

### PR DESCRIPTION
**Pull request by felixlopz**
https://github.com/HubRise/website/issues/896

### CODE REVIEW

**Review by antmonnier — COMMENTED** [review]
Minor thing, but I think you could just test (and export) `doesSearchTextMatch`. The tests for `normalizeText` look a bit redundant, and they could be merged with the others. I'm leaving you the final word, do what you prefer.

**Comment by felixlopz** [comment]
Hey @antmonnier yeah, glad you mentioned this I also felt it was a bit redundant, I removed the tests for `normalizeText`

**Review by antmonnier — COMMENTED** [review]
1. Just to be picky, the remaining expectaions could be organised in distinct, well labeled test cases, such as "does not always return true", "ignores accents", "ignore spaces", "ignore dots". This will make the behaviour more obvious, and increase confidence.

2. You don't need to export `normalizeText` any more.

**Comment by felixlopz** [comment]
okay updated the tests! lmk if there is any more changes!

**Pull request merged**
