### PR TITLE
Documentation mobile improvements (#50)

### PR DESCRIPTION
**Pull request by Ozerich**

### CODE REVIEW

**Comment by Ozerich** [comment]
Ready to merge

**Comment by antmonnier** [comment]
Closes #50

**Comment by antmonnier** [comment]
Thanks,

- http://localhost:8000/apps/ikentoo/integration-guide/ : flickers when you scroll down on mobile

- call-summary: there should be one single horizontal scrollbar for the whole table instead of one scrollbar for every cell:
image

**Comment by Ozerich** [comment]
Fixed

**Pull request merged**
