### PR TITLE
[Uber Eats] Webstore support

### PR DESCRIPTION
**Pull request by janaina-wittner**
We need to update the online documentation with the information we will get on the connection of the Uber Eats white label Webstore offer.

### CODE REVIEW

**Comment by janaina-wittner** [comment]
@antmonnier, that's the whole point... I want the limitations to be documented. So once we have a client that asks about it again, we can send them to the page which will explain the issues. They can decide to go ahead with it despite the limitations.

**Comment by janaina-wittner** [comment]
You improve the post, or shall I?
You told me not to open old projects :-(

**Comment by antmonnier** [comment]
Ok, I'll create a FAQ then

**Comment by antmonnier** [comment]
Done cc @janaina-wittner

**Pull request merged**
