### PR TITLE
Feature/content organization

### PR DESCRIPTION
**Pull request by Ozerich**

### CODE REVIEW

**Comment by Ozerich** [comment]
To make things working I replace url "/developpeurs" by "/developers" and add redirect from "/developers/api/" to "/developers/api/general-concepts/"

**Comment by antmonnier** [comment]
Hi @Ozerich 

I've noticed an issue: when I set `path_override: developpeurs` in `content/developers/fr/customization.yaml`, pages are still generated under `/fr/developers/api/xxx` instead of `/fr/developpeurs/api/xxx`

Could it help to enforce a more object oriented approach, ie see md pages and file folders as objects in a tree structure, and let each page object generate its own rendering, breadcrumb, etc. Maybe that would also allow more atomic testing: we could load a simple test tree structure and check that breadcrumb generation works the way it should, etc. What do you think?

**Comment by Saranchenkov** [comment]
I've fixed issue with `path_override: developpeurs`
Also I suggest to do rewriting to OOP approach and automatic redirects as separate task. 
_My approximate estimation_: **12h**

**Comment by Ozerich** [comment]
I've fixed issue with `path_override: developpeurs`
Also I suggest to do rewriting to OOP approach and automatic redirects as separate task.
_My approximate estimation_: **12h**

**Pull request merged**
