### PR TITLE
[ADIPOS] smood inclusion

### PR DESCRIPTION
**Pull request by janaina-wittner**

### CODE REVIEW

**Comment by janaina-wittner** [comment]
@antmonnier, this is ready to be merged

**Comment by antmonnier** [comment]
Todo before merging: include instructions to connect autonomously to HubRise.

**Comment by janaina-wittner** [comment]
Hi @antmonnier, I was aware that we were missing this information but seeing how Adipos works I think clients will NEVER connect autonomously. They do everything for them. Even connect to the SMOOD back office to connect Smood to HubRise for them !

**Comment by janaina-wittner** [comment]
@antmonnier, could this be merged?

**Pull request merged**
