### PR TITLE
[SOS SOIREE & CLYO] image & other tiny updates

### PR DESCRIPTION
**Pull request by janaina-wittner**

### CODE REVIEW

**Comment by janaina-wittner** [comment]
@antmonnier, this is ready for merge.

**Comment by janaina-wittner** [comment]
@antmonnier, ups, wait a minute, I have more images to load I had almost forgotten.

**Comment by janaina-wittner** [comment]
@antmonnier, you can go ahead and publish it now.

**Comment by antmonnier** [comment]
@janaina-wittner I've converted the blog banners from PNG to JPG, which decrease their size from 2-6Mb to 200-400kb.

**Pull request merged**
